# -*- coding: utf-8 -*-
"""PythonGrupo8 PARTE 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cV4ZtQmve4lnZnYLhctZbKgtJzj94kcw
"""

# ═══════════════════════════════════════════════════════════════

# PASO 1: CONFIGURACIÓN Y CARGA DE DATOS

# ═══════════════════════════════════════════════════════════════

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

import warnings

import re

from datetime import datetime

import os

import unicodedata

import re

import json

from datetime import datetime

warnings.filterwarnings('ignore')

sns.set_style('whitegrid')

plt.rcParams['figure.figsize'] = (12, 6)

pd.set_option('display.max_columns', None)

print("╔════════════════════════════════════════════════════════════╗")

print("║   DATA PREPARATION - Encuesta SSPD                        ║")

print("╚════════════════════════════════════════════════════════════╝")

print(f"\n📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# Cargar datos

print("📂 Cargando datos...")

df_raw = pd.read_excel('/content/base_datos_completa_NNA_TI_anon.xlsx', sheet_name='BD', engine='openpyxl')

print(f"✅ Cargados: {df_raw.shape[0]:,} registros × {df_raw.shape[1]} columnas\n")


# ═══════════════════════════════════════════════════════════════

# PASO 2: ESTANDRIZACIÓN DE NOMBRES DE COLUMNAS

# ═══════════════════════════════════════════════════════════════

print("="*70)

print("🔧 PASO 1: estandarizando nombres de columnas")

print("="*70 + "\n")

def normalize_columns(df):

    """estandariza nombres: elimina espacios extras y estandariza"""

    new_cols = []

    for col in df.columns:

        # Limpiar espacios

        col_clean = str(col).strip()

        col_clean = re.sub(r'\s+', ' ', col_clean)

        # Reemplazar espacios por guión bajo

        col_clean = col_clean.replace(' ', '_')

        new_cols.append(col_clean)

    return new_cols

df = df_raw.copy()

df.columns = normalize_columns(df)

print(f"✓ Columnas estandarizadas: {len(df.columns)}")

# ═══════════════════════════════════════════════════════════════
# PASO 2: ESTANDRIZACIÓN DE NOMBRES DE COLUMNAS
# ═══════════════════════════════════════════════════════════════

print("="*70)
print("🔧 PASO 1: estandarizando nombres de columnas")
print("="*70 + "\n")

def normalize_columns(df):
    """estandariza nombres: elimina espacios extras y estandariza"""
    new_cols = []
    for col in df.columns:
        # Limpiar espacios
        col_clean = str(col).strip()
        col_clean = re.sub(r'\s+', ' ', col_clean)
        # Reemplazar espacios por guión bajo
        col_clean = col_clean.replace(' ', '_')
        new_cols.append(col_clean)
    return new_cols

df = df_raw.copy()
df.columns = normalize_columns(df)
print(f"✓ Columnas estandarizadas: {len(df.columns)}")

df.head()

# ═══════════════════════════════════════════════════════════════
# PASO 3: ELIMINACIÓN DE DATOS PERSONALES (PII)
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("🔒 PASO 2: Eliminando información personal identificable (PII)")
print("="*70 + "\n")

# Columnas PII identificadas en el análisis
PII_COLUMNS = [
    "Id_fic",
    "CORREO_1",
    "CORREO_2",
    "TELÉFONO_1",
    "TELÉFONO_2",
    ]

cols_to_drop = [c for c in PII_COLUMNS if c in df.columns]
print(f"🔍 Columnas PII encontradas: {len(cols_to_drop)}")
for col in cols_to_drop:
    print(f"   ❌ {col}")

df_clean = df.drop(columns=cols_to_drop)
print(f"\n✓ Dataset seguro: {df_clean.shape[0]:,} × {df_clean.shape[1]} columnas")

df_clean.head()

# ═══════════════════════════════════════════════════════════════
# PASO 4: MANEJO DE VALORES FALTANTES
# ═══════════════════════════════════════════════════════════════

# --- 1) Reemplazar vacíos y 99999 por NaN ---
# Define textos o códigos que indican faltantes
missing_tokens = ["", " ", "NA", "N/A", "na", "n/a", "NaN", "null", "NULL",
                  "None", "SIN DATO", "SIN_DATO", "sd", "s/d", 99999, "99999"]

df_clean = df_clean.replace(missing_tokens, np.nan)

# --- 2) Crear resumen de faltantes ---
missing_summary = (
    pd.DataFrame({
        "Variable": df_clean.columns,
        "Faltantes": df_clean.isna().sum(),
        "Porcentaje": (df_clean.isna().sum() / len(df_clean) * 100).round(2)
    })
    .sort_values("Porcentaje", ascending=False)
    .reset_index(drop=True)
)

print("📊 RESUMEN DE VALORES FALTANTES")
print(missing_summary.head(20).to_string(index=False))  # muestra las 20 primeras

# --- 3) Visualización rápida ---
plt.figure(figsize=(8,6))
top_vars = missing_summary.head(15)
plt.barh(top_vars["Variable"], top_vars["Porcentaje"], color='steelblue')
plt.xlabel("% de valores faltantes")
plt.ylabel("Variable")
plt.title("Top 15 variables con mayor porcentaje de faltantes")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# --- 4) Guardar resumen (opcional) ---
missing_summary.to_csv("/content/resumen_faltantes.csv", index=False, encoding="utf-8-sig")

print("\n✅ Archivo 'resumen_faltantes.csv' guardado en tu carpeta de trabajo.")

# ═══════════════════════════════════════════════════════════════
# PASO 5: SELECCIÓN DE VARIABLES
# ═══════════════════════════════════════════════════════════════

# Lista exacta de variables a conservar
columnas_seleccionadas = [
    "NOMBRE_EAPB",
    "AFILIACIÓN_AL_SGSSS",
    "LOCALIDAD",
    "OCUPACIÓN",
    "SEXO",
    "VÍNCULO_CON_EL_JEFE_DE_HOGAR",
    "POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN",
    "Localidad_fic",
    "ESTRATO",
    "NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL",
    "¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?",
    "ESTRATO_SOCIOECONÓMICO"
]

# --- 1) Verificar coincidencias exactas ---
# Algunos nombres pueden tener espacios, tildes o caracteres ocultos.
# Vamos a imprimir los que sí existen y los que no.
cols_existentes = [col for col in columnas_seleccionadas if col in df_clean.columns]
cols_faltantes = [col for col in columnas_seleccionadas if col not in df_clean.columns]

print("✅ Variables encontradas en la base:")
print(cols_existentes)
print("\n⚠️ Variables NO encontradas (revisa nombres exactos):")
print(cols_faltantes)

# --- 2) Crear el nuevo DataFrame solo con las columnas encontradas ---
df_subset = df_clean[cols_existentes].copy()

print(f"\n📋 Nuevo DataFrame creado con {df_subset.shape[1]} columnas y {df_subset.shape[0]} filas.")

# --- 3) (Opcional) Guardar el resultado ---
df_subset.to_excel("/content/df_subset_variables_seleccionadas.xlsx", index=False)
print("💾 Archivo guardado: df_subset_variables_seleccionadas.xlsx")

df_subset.head()

# ═══════════════════════════════════════════════════════════════
# PASO 6: CONSTRUCCIÓN DE VARIABLES DERIVADAS
# ═══════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════
# TABLAS DE CRUCES (crosstabs) — % POR FILA (NOMBRES EXACTOS)
# ═══════════════════════════════════════════════════════════════

import pandas as pd

# Cruces EXACTOS (con tildes, guiones bajos y signos tal cual)
CRUCES = [
    ("SEXO", "VÍNCULO_CON_EL_JEFE_DE_HOGAR"),
    ("OCUPACIÓN", "SEXO"),
    ("NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL", "SEXO"),
    ("LOCALIDAD", "¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?"),
    ("LOCALIDAD", "POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN"),
    ("VÍNCULO_CON_EL_JEFE_DE_HOGAR", "SEXO"),
]

# Verificación de columnas faltantes
todas = set(sum(([a, b] for a, b in CRUCES), []))
faltan = [c for c in todas if c not in df_subset.columns]
if faltan:
    raise KeyError(f"Estas columnas NO existen en df_subset: {faltan}\n"
                   f"Revisa df_subset.columns para ver los nombres tal cual.")

# Construir tablas (% por fila)
tablas = {}
for A, B in CRUCES:
    tb = pd.crosstab(
        df_subset[A].astype("string"),
        df_subset[B].astype("string"),
        normalize="index"
    ) * 100
    tb = tb.round(2)
    nombre = f"{A}__x__{B}"
    tablas[nombre] = tb
    print(f"📊 {nombre}:\n", tb.head(), "\n")

sns.set(style="whitegrid", palette="pastel")

# --- Lista de cruces con nombres EXACTOS ---
CRUCES = [
    ("SEXO", "VÍNCULO_CON_EL_JEFE_DE_HOGAR"),
    ("OCUPACIÓN", "SEXO"),
    ("NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL", "SEXO"),
    ("LOCALIDAD", "¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?"),
    ("LOCALIDAD", "POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN"),
    ("VÍNCULO_CON_EL_JEFE_DE_HOGAR", "SEXO"),
]

# --- Gráfico de barras agrupadas para cada cruce ---
for A, B in CRUCES:
    # Validar existencia de las columnas
    if A not in df_subset.columns or B not in df_subset.columns:
        print(f"⚠️ No se encontró alguna columna: {A} o {B}")
        continue

    # Tabla % por fila
    tb = pd.crosstab(df_subset[A].astype("string"),
                     df_subset[B].astype("string"),
                     normalize="index") * 100
    tb = tb.round(2)

    # Convertir a formato largo para graficar
    df_long = tb.reset_index().melt(id_vars=A,
                                    var_name=B,
                                    value_name="Porcentaje")

    # Crear gráfico
    plt.figure(figsize=(10, 5))
    sns.barplot(data=df_long, x=A, y="Porcentaje", hue=B)

    plt.title(f"{A.replace('_', ' ')} × {B.replace('_', ' ')}")
    plt.xlabel(A.replace('_', ' '))
    plt.ylabel("% dentro de cada categoría de " + A.split('_')[0])
    plt.xticks(rotation=45, ha="right")
    plt.legend(title=B.replace('_', ' '), bbox_to_anchor=(1.02, 1), loc="upper left")
    plt.tight_layout()
    plt.show()

# ═══════════════════════════════════════════════════════════════
# PASO 7: ESTRUCTURACIÓN FINAL – BASE DE TRABAJO INFANTIL
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("📋 PASO 7: Estructurando base final de trabajo infantil")
print("="*70 + "\n")

# --- 1️⃣ Definir los grupos temáticos ---
GRUPOS_ORDENADOS = {
    "Identificación": [
        "NOMBRE_EAPB",
        "AFILIACIÓN_AL_SGSSS"
    ],
    "Demografia": [
        "SEXO",
        "OCUPACIÓN",
        "VÍNCULO_CON_EL_JEFE_DE_HOGAR",
        "POBLACION_DIFERENCIAL_Y_DE_INCLUSIONES"
    ],
    "Condiciones_Socioeconomicas": [
        "ESTRATO",
        "ESTRATO_SOCIOECONÓMICO",
        "NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL"
    ],
    "Territorial": [
        "LOCALIDAD",
        "Localidad_fic",
        "¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?"
    ],
    "Cruces_Analíticos": [
        # Puedes crear estas nuevas variables si ya calculaste las combinaciones
        "SEXO_x_VÍNCULO_CON_EL_JEFE_DE_HOGAR",
        "OCUPACIÓN_x_SEXO",
        "NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL_x_SEXO",
        "LOCALIDAD_x_¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?",
        "LOCALIDAD_x_POBLACION_DIFERENCIAL_Y_DE_INCLUSIONES",
        "VÍNCULO_CON_EL_JEFE_DE_HOGAR_x_SEXO"
    ]
}

# --- 2️⃣ Crear lista ordenada de columnas ---
columnas_ordenadas = []

for grupo, cols in GRUPOS_ORDENADOS.items():
    for col in cols:
        if col in df_subset.columns and col not in columnas_ordenadas:
            columnas_ordenadas.append(col)

# --- 3️⃣ Agregar columnas no clasificadas ---
for col in df_subset.columns:
    if col not in columnas_ordenadas:
        columnas_ordenadas.append(col)

# --- 4️⃣ Crear DataFrame final ordenado ---
df_final = df_subset[columnas_ordenadas].copy()

# --- 5️⃣ Mostrar resumen de agrupación ---
print(f"✓ Columnas reordenadas por grupos temáticos ({len(columnas_ordenadas)} columnas totales)\n")

for grupo, cols in GRUPOS_ORDENADOS.items():
    existentes = [c for c in cols if c in df_subset.columns]
    print(f"  • {grupo}: {len(existentes)} / {len(cols)} columnas encontradas")

display(df_final.head())

# ═══════════════════════════════════════════════════════════════
# PASO 9: EXPORTAR RESULTADOS
# ═══════════════════════════════════════════════════════════════

print("="*70)
print("💾 PASO 9: Exportando resultados – Base trabajo infantil")
print("="*70 + "\n")

# --- 1️⃣ Crear carpetas de salida ---
os.makedirs('data/procesados', exist_ok=True)
os.makedirs('reports', exist_ok=True)

# --- 2️⃣ Exportar CSV limpio ---
output_csv = 'data/procesados/Base_NNA_trabajo_infantil.csv'
df_final.to_csv(output_csv, index=False, encoding='utf-8-sig')
size_csv = os.path.getsize(output_csv) / 1024**2
print(f"✓ CSV exportado: {output_csv} ({size_csv:.2f} MB)")

# --- 3️⃣ Exportar Excel limpio ---
output_excel = 'data/procesados/Base_NNA_trabajo_infantil.xlsx'
df_final.to_excel(output_excel, index=False, engine='openpyxl')
size_excel = os.path.getsize(output_excel) / 1024**2
print(f"✓ Excel exportado: {output_excel} ({size_excel:.2f} MB)")

# --- 4️⃣ Crear diccionario de datos ---
data_dict = pd.DataFrame({
    'Columna': df_final.columns,
    'Tipo': df_final.dtypes.astype(str).values,
    'No_Nulos': df_final.notnull().sum().values,
    'Nulos': df_final.isnull().sum().values,
    'Pct_Nulos': (df_final.isnull().sum() / len(df_final) * 100).round(2).values,
    'Valores_Unicos': [df_final[col].nunique() for col in df_final.columns],
})
data_dict.to_csv('reports/diccionario_datos_NNA.csv', index=False, encoding='utf-8-sig')
print("✓ Diccionario de datos: reports/diccionario_datos_NNA.csv")

# --- 5️⃣ Generar reporte de transformaciones ---
total_nulls = int(df_final.isnull().sum().sum())
pct_nulls = round((total_nulls / (df_final.shape[0] * df_final.shape[1]) * 100), 2)

reporte = {
    'fecha_proceso': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'dataset_final': {
        'filas': int(df_final.shape[0]),
        'columnas': int(df_final.shape[1]),
    },
    'proceso': "Limpieza, estructuración y análisis de base de trabajo infantil (NNA)",
    'resumen': {
        'valores_faltantes': total_nulls,
        'porcentaje_faltantes': pct_nulls,
        'duplicados': int(df_final.duplicated().sum()),
    },
    'exportaciones_realizadas': {
        'csv': output_csv,
        'excel': output_excel,
        'diccionario_datos': 'reports/diccionario_datos_NNA.csv',
    },
    'grupos_tematicos': [
        "Identificación",
        "Demografía",
        "Condiciones_Socioeconómicas",
        "Territorial",
        "Cruces_Analíticos",
    ],
    'variables_destacadas': list(df_final.columns[:10])  # muestra las primeras 10
}

with open('reports/reporte_transformaciones_NNA.json', 'w', encoding='utf-8') as f:
    json.dump(reporte, f, indent=2, ensure_ascii=False)

print("✓ Reporte general: reports/reporte_transformaciones_NNA.json")

print("\n✅ Exportación completada exitosamente.")

# ═══════════════════════════════════════════════════════════════
# PASO 10: VISUALIZACIONES FINALES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("📊 Generando visualizaciones comparativas")
print("="*70 + "\n")

# Comparación antes/después
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# 1. Dimensiones
cat = ['Original', 'Final']
filas = [df_raw.shape[0], df_final.shape[0]]
cols = [df_raw.shape[1], df_final.shape[1]]

axes[0].bar(cat, cols, color=['#e74c3c', '#27ae60'])
axes[0].set_title('Número de Columnas', fontweight='bold')
axes[0].set_ylabel('Columnas')
for i, v in enumerate(cols):
    axes[0].text(i, v+1, str(v), ha='center', fontweight='bold')

# 2. Distribución por sexo (en lugar de grupo_edad)
if 'SEXO' in df_final.columns:
    sexo_dist = df_final['SEXO'].value_counts()
    axes[1].barh(range(len(sexo_dist)), sexo_dist.values, color='#3498db')
    axes[1].set_yticks(range(len(sexo_dist)))
    axes[1].set_yticklabels(sexo_dist.index, fontsize=9)
    axes[1].set_title('Distribución: Sexo', fontweight='bold')
    axes[1].set_xlabel('Frecuencia')
    axes[1].invert_yaxis()

# 3. Distribución por ocupación (en lugar de categoria_problema)
if 'OCUPACIÓN' in df_final.columns:
    ocup_dist = df_final['OCUPACIÓN'].value_counts().head(8)  # Top 8
    axes[2].bar(range(len(ocup_dist)), ocup_dist.values, color='#e67e22')
    axes[2].set_xticks(range(len(ocup_dist)))
    axes[2].set_xticklabels([str(label)[:15] + '...' if len(str(label)) > 15 else str(label)
                           for label in ocup_dist.index], rotation=45, ha='right', fontsize=8)
    axes[2].set_title('Distribución: Ocupación (Top 8)', fontweight='bold')
    axes[2].set_ylabel('Frecuencia')

plt.tight_layout()
plt.savefig('reports/comparacion_final.png', dpi=300, bbox_inches='tight')
print("✓ Visualización: reports/comparacion_final.png")
plt.show()


# ═══════════════════════════════════════════════════════════════
# RESUMEN FINAL
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("✨ DATA PREPARATION COMPLETADA ✨")
print("="*70 + "\n")

# Contar variables derivadas creadas (basado en los cruces analíticos)
variables_derivadas = []
for A, B in CRUCES:
    variables_derivadas.append(f"{A}__x__{B}")

print("📊 RESUMEN DE TRANSFORMACIONES:\n")
print(f"   Original: {df_raw.shape[0]:,} × {df_raw.shape[1]} columnas")
print(f"   Final: {df_final.shape[0]:,} × {df_final.shape[1]} columnas")
print(f"   Eliminadas: {len(cols_to_drop)} columnas PII")
print(f"   Creadas: {len(variables_derivadas)} tablas de cruces analíticos")

print(f"\n📁 ARCHIVOS GENERADOS:")
print(f"   ✓ data/procesados/Base_NNA_trabajo_infantil.csv")
print(f"   ✓ data/procesados/Base_NNA_trabajo_infantil.xlsx")
print(f"   ✓ reports/diccionario_datos_NNA.csv")
print(f"   ✓ reports/reporte_transformaciones_NNA.json")
print(f"   ✓ reports/comparacion_final.png")

print(f"\n🔑 VARIABLES CLAVE EN EL ANÁLISIS:")
variables_clave = [
    "SEXO",
    "OCUPACIÓN",
    "LOCALIDAD",
    "NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL",
    "POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN"
]
for var in variables_clave:
    if var in df_final.columns:
        print(f"   • {var}")

print(f"\n📊 TABLAS DE CRUCES GENERADAS:")
for A, B in CRUCES:
    print(f"   • {A} × {B}")

print(f"\n🎯 DATASET LISTO PARA ANÁLISIS DE:")
print(f"   • Trabajo infantil y desvinculación laboral")
print(f"   • Distribución demográfica por sexo y ocupación")
print(f"   • Análisis territorial por localidad")
print(f"   • Población diferencial y de inclusión")
print(f"   • Condiciones socioeconómicas y estratificación")

print("\n" + "="*70)
print(f"📅 Finalizado: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("="*70 + "\n")

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
╔═══════════════════════════════════════════════════════════════╗
║  ANÁLISIS 1: PERFIL DEMOGRÁFICO Y LABORAL DE NNA             ║
║  Base NNA - Trabajo Infantil                                 ║
╚═══════════════════════════════════════════════════════════════╝

Objetivo: Analizar características demográficas y condiciones laborales de NNA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os

# Configuración
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (14, 8)

print("╔════════════════════════════════════════════════════════════╗")
print("║   ANÁLISIS DEMOGRÁFICO Y LABORAL DE NNA                   ║")
print("╚════════════════════════════════════════════════════════════╝")
print(f"\n📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# ═══════════════════════════════════════════════════════════════
# 1. CARGAR DATOS PREPARADOS
# ═══════════════════════════════════════════════════════════════

print("📂 Cargando datos preparados...")
df = pd.read_csv('data/procesados/Base_NNA_trabajo_infantil.csv')
print(f"✓ Datos cargados: {df.shape[0]:,} registros\n")

# ═══════════════════════════════════════════════════════════════
# 2. ANÁLISIS DESCRIPTIVO DEMOGRÁFICO
# ═══════════════════════════════════════════════════════════════

print("="*70)
print("📊 ANÁLISIS DESCRIPTIVO DEMOGRÁFICO")
print("="*70 + "\n")

# Variables clave del dataset NNA
sexo_col = 'SEXO'
ocupacion_col = 'OCUPACIÓN'
vinculo_col = 'VÍNCULO_CON_EL_JEFE_DE_HOGAR'
poblacion_diff_col = 'POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN'
desvinculado_col = 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'
localidad_col = 'LOCALIDAD'
lugar_trabajo_col = '¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?'

# 1. Distribución por sexo
print("1️⃣  DISTRIBUCIÓN POR SEXO:\n")
if sexo_col in df.columns:
    dist_sexo = df[sexo_col].value_counts()
    pct_sexo = df[sexo_col].value_counts(normalize=True) * 100
    for sexo, count in dist_sexo.items():
        print(f"   • {sexo}: {count} ({pct_sexo[sexo]:.1f}%)")

# 2. Distribución por ocupación
print("\n\n2️⃣  DISTRIBUCIÓN POR OCUPACIÓN (Top 10):\n")
if ocupacion_col in df.columns:
    dist_ocup = df[ocupacion_col].value_counts().head(10)
    pct_ocup = df[ocupacion_col].value_counts(normalize=True).head(10) * 100
    for ocup, count in dist_ocup.items():
        print(f"   • {ocup}: {count} ({pct_ocup[ocup]:.1f}%)")

# 3. Vínculo con jefe de hogar
print("\n\n3️⃣  VÍNCULO CON EL JEFE DE HOGAR:\n")
if vinculo_col in df.columns:
    dist_vinculo = df[vinculo_col].value_counts()
    pct_vinculo = df[vinculo_col].value_counts(normalize=True) * 100
    for vinculo, count in dist_vinculo.items():
        print(f"   • {vinculo}: {count} ({pct_vinculo[vinculo]:.1f}%)")

# ═══════════════════════════════════════════════════════════════
# 3. ANÁLISIS DE TRABAJO INFANTIL
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("🔍 ANÁLISIS DE TRABAJO INFANTIL")
print("="*70 + "\n")

# 1. NNA desvinculados de actividad laboral
print("1️⃣  NNA DESVINCULADOS DE ACTIVIDAD LABORAL:\n")
if desvinculado_col in df.columns:
    dist_desv = df[desvinculado_col].value_counts()
    pct_desv = df[desvinculado_col].value_counts(normalize=True) * 100
    for estado, count in dist_desv.items():
        print(f"   • {estado}: {count} ({pct_desv[estado]:.1f}%)")

    # Análisis crítico
    if 'Sí' in dist_desv.index:
        nna_trabajando = dist_desv['Sí']
        pct_trabajando = pct_desv['Sí']
        print(f"\n   ⚠️  ALERTA: {nna_trabajando} NNA ({pct_trabajando:.1f}%) trabajan")

# 2. Lugar principal de trabajo
print("\n\n2️⃣  LUGAR PRINCIPAL DE TRABAJO:\n")
if lugar_trabajo_col in df.columns:
    dist_lugar = df[lugar_trabajo_col].value_counts()
    pct_lugar = df[lugar_trabajo_col].value_counts(normalize=True) * 100
    for lugar, count in dist_lugar.items():
        if pd.notna(lugar):
            print(f"   • {lugar}: {count} ({pct_lugar[lugar]:.1f}%)")

# 3. Población diferencial
print("\n\n3️⃣  POBLACIÓN DIFERENCIAL Y DE INCLUSIÓN:\n")
if poblacion_diff_col in df.columns:
    dist_pobl = df[poblacion_diff_col].value_counts().head(10)
    pct_pobl = df[poblacion_diff_col].value_counts(normalize=True).head(10) * 100
    for pobl, count in dist_pobl.items():
        if pd.notna(pobl):
            print(f"   • {pobl}: {count} ({pct_pobl[pobl]:.1f}%)")

# ═══════════════════════════════════════════════════════════════
# 4. ANÁLISIS POR LOCALIDAD
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("🗺️  DISTRIBUCIÓN POR LOCALIDAD")
print("="*70 + "\n")

if localidad_col in df.columns:
    print("📍 DISTRIBUCIÓN POR LOCALIDAD (Top 10):\n")
    dist_localidad = df[localidad_col].value_counts().head(10)
    pct_localidad = df[localidad_col].value_counts(normalize=True).head(10) * 100
    for localidad, count in dist_localidad.items():
        print(f"   • {localidad}: {count} ({pct_localidad[localidad]:.1f}%)")

# ═══════════════════════════════════════════════════════════════
# 5. CRUCES ANALÍTICOS
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("📊 CRUCES ANALÍTICOS CLAVE")
print("="*70 + "\n")

# Cruce 1: Sexo vs Desvinculación laboral
if sexo_col in df.columns and desvinculado_col in df.columns:
    print("1️⃣  SEXO vs DESVINCULACIÓN LABORAL:\n")
    crosstab_sexo_desv = pd.crosstab(df[sexo_col], df[desvinculado_col], normalize='index') * 100
    print(crosstab_sexo_desv.round(1).to_string())

# Cruce 2: Ocupación vs Sexo
if ocupacion_col in df.columns and sexo_col in df.columns:
    print("\n\n2️⃣  OCUPACIÓN vs SEXO (Top 5 ocupaciones):\n")
    top_ocupaciones = df[ocupacion_col].value_counts().head(5).index
    df_top = df[df[ocupacion_col].isin(top_ocupaciones)]
    crosstab_ocup_sexo = pd.crosstab(df_top[ocupacion_col], df_top[sexo_col], normalize='index') * 100
    print(crosstab_ocup_sexo.round(1).to_string())

# ═══════════════════════════════════════════════════════════════
# 6. VISUALIZACIONES
# ═══════════════════════════════════════════════════════════════

os.makedirs('reports/perfil_nna', exist_ok=True)

print("\n\n" + "="*70)
print("📊 Generando visualizaciones...")
print("="*70 + "\n")

# Gráfico 1: Dashboard demográfico y laboral
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1.1 Distribución por sexo
if sexo_col in df.columns:
    dist_sexo = df[sexo_col].value_counts()
    axes[0,0].pie(dist_sexo.values, labels=dist_sexo.index, autopct='%1.1f%%', startangle=90)
    axes[0,0].set_title('Distribución por Sexo', fontsize=12, fontweight='bold')

# 1.2 NNA desvinculados laboralmente
if desvinculado_col in df.columns:
    dist_desv = df[desvinculado_col].value_counts()
    colors = {'Sí': '#e74c3c', 'No': '#27ae60', 'other': '#95a5a6'}
    col_map = [colors.get(x, '#95a5a6') for x in dist_desv.index]
    axes[0,1].bar(range(len(dist_desv)), dist_desv.values, color=col_map)
    axes[0,1].set_xticks(range(len(dist_desv)))
    axes[0,1].set_xticklabels(dist_desv.index)
    axes[0,1].set_ylabel('Frecuencia', fontweight='bold')
    axes[0,1].set_title('NNA Desvinculados de Actividad Laboral', fontsize=12, fontweight='bold')
    for i, v in enumerate(dist_desv.values):
        axes[0,1].text(i, v + 0.1, str(v), ha='center', fontweight='bold')

# 1.3 Top ocupaciones
if ocupacion_col in df.columns:
    top_ocup = df[ocupacion_col].value_counts().head(8)
    axes[1,0].barh(range(len(top_ocup)), top_ocup.values, color='#3498db')
    axes[1,0].set_yticks(range(len(top_ocup)))
    axes[1,0].set_yticklabels([str(ocup)[:20] + '...' if len(str(ocup)) > 20 else str(ocup)
                              for ocup in top_ocup.index], fontsize=9)
    axes[1,0].set_xlabel('Frecuencia', fontweight='bold')
    axes[1,0].set_title('Principales Ocupaciones (Top 8)', fontsize=12, fontweight='bold')
    axes[1,0].invert_yaxis()

# 1.4 Distribución por localidad (Top 5)
if localidad_col in df.columns:
    top_localidades = df[localidad_col].value_counts().head(5)
    axes[1,1].pie(top_localidades.values, labels=top_localidades.index, autopct='%1.1f%%', startangle=90)
    axes[1,1].set_title('Distribución por Localidad (Top 5)', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('reports/perfil_nna/01_dashboard_demografico.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: reports/perfil_nna/01_dashboard_demografico.png")
plt.close()

# Gráfico 2: Cruces analíticos
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 2.1 Sexo vs Desvinculación laboral
if sexo_col in df.columns and desvinculado_col in df.columns:
    crosstab = pd.crosstab(df[sexo_col], df[desvinculado_col])
    crosstab.plot(kind='bar', ax=axes[0], color=['#27ae60', '#e74c3c'])
    axes[0].set_title('Sexo vs Desvinculación Laboral', fontsize=12, fontweight='bold')
    axes[0].set_xlabel('Sexo', fontweight='bold')
    axes[0].set_ylabel('Frecuencia', fontweight='bold')
    axes[0].legend(title='Desvinculado', bbox_to_anchor=(1.05, 1), loc='upper left')
    axes[0].tick_params(axis='x', rotation=45)

# 2.2 Ocupación vs Sexo (Top 5)
if ocupacion_col in df.columns and sexo_col in df.columns:
    top_ocupaciones = df[ocupacion_col].value_counts().head(5).index
    df_top = df[df[ocupacion_col].isin(top_ocupaciones)]
    crosstab = pd.crosstab(df_top[ocupacion_col], df_top[sexo_col])
    crosstab.plot(kind='bar', ax=axes[1], stacked=True)
    axes[1].set_title('Ocupación vs Sexo (Top 5)', fontsize=12, fontweight='bold')
    axes[1].set_xlabel('Ocupación', fontweight='bold')
    axes[1].set_ylabel('Frecuencia', fontweight='bold')
    axes[1].legend(title='Sexo', bbox_to_anchor=(1.05, 1), loc='upper left')
    axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('reports/perfil_nna/02_cruces_analiticos.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: reports/perfil_nna/02_cruces_analiticos.png")
plt.close()

# Gráfico 3: Heatmap de ocupación por sexo
if ocupacion_col in df.columns and sexo_col in df.columns:
    fig, ax = plt.subplots(figsize=(12, 8))
    top_ocup_heat = df[ocupacion_col].value_counts().head(10).index
    df_heat = df[df[ocupacion_col].isin(top_ocup_heat)]
    heatmap_data = pd.crosstab(df_heat[ocupacion_col], df_heat[sexo_col], normalize='index') * 100

    sns.heatmap(heatmap_data, annot=True, fmt='.1f', cmap='YlOrRd',
                cbar_kws={'label': 'Porcentaje (%)'}, ax=ax, linewidths=0.5)
    ax.set_title('Distribución de Sexo por Ocupación (%)', fontsize=14, fontweight='bold', pad=20)
    ax.set_xlabel('Sexo', fontweight='bold')
    ax.set_ylabel('Ocupación', fontweight='bold')
    plt.tight_layout()
    plt.savefig('reports/perfil_nna/03_heatmap_ocupacion_sexo.png', dpi=300, bbox_inches='tight')
    print("✓ Guardado: reports/perfil_nna/03_heatmap_ocupacion_sexo.png")
    plt.close()

# ═══════════════════════════════════════════════════════════════
# 7. INSIGHTS Y RECOMENDACIONES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("💡 INSIGHTS Y RECOMENDACIONES")
print("="*70 + "\n")

# Hallazgos clave
print("📊 HALLAZGOS CLAVE:\n")

if desvinculado_col in df.columns and 'Sí' in df[desvinculado_col].value_counts().index:
    nna_trabajando = df[desvinculado_col].value_counts()['Sí']
    pct_trabajando = (nna_trabajando / len(df) * 100)
    print(f"1. {pct_trabajando:.1f}% de NNA están trabajando ({nna_trabajando} casos)")

    if pct_trabajando > 5:
        print("   ⚠️  ALERTA: Presencia significativa de trabajo infantil")

if sexo_col in df.columns:
    distribucion_sexo = df[sexo_col].value_counts(normalize=True) * 100
    sexo_mayoritario = distribucion_sexo.idxmax()
    pct_mayoritario = distribucion_sexo.max()
    print(f"2. Distribución por sexo: {sexo_mayoritario} ({pct_mayoritario:.1f}%)")

if ocupacion_col in df.columns:
    ocupacion_principal = df[ocupacion_col].value_counts().index[0]
    print(f"3. Ocupación principal: {ocupacion_principal}")

print("\n\n🎯 RECOMENDACIONES:\n")
print("1. Fortalecer programas de prevención de trabajo infantil")
print("2. Implementar estrategias diferenciadas por sexo")
print("3. Focalizar intervenciones en ocupaciones de mayor riesgo")
print("4. Desarrollar programas de reintegración educativa")
print("5. Establecer sistemas de monitoreo y seguimiento")

# Exportar resumen
resumen = {
    'fecha_analisis': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'total_registros': int(len(df)),
    'nna_trabajando': int(nna_trabajando) if 'nna_trabajando' in locals() else 0,
    'pct_trabajando': float(round(pct_trabajando, 2)) if 'pct_trabajando' in locals() else 0,
    'distribucion_sexo': dict(distribucion_sexo.round(2)) if 'distribucion_sexo' in locals() else {}
}

import json
with open('reports/perfil_nna/resumen.json', 'w', encoding='utf-8') as f:
    json.dump(resumen, f, indent=2, ensure_ascii=False)

print("\n✓ Resumen exportado: reports/perfil_nna/resumen.json")

print("\n" + "="*70)
print("✅ ANÁLISIS DEMOGRÁFICO Y LABORAL DE NNA COMPLETADO")
print("="*70 + "\n")

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
╔═══════════════════════════════════════════════════════════════╗
║  ANÁLISIS 2: SEGMENTACIÓN DEMOGRÁFICA Y TERRITORIAL          ║
║  Base NNA - Trabajo Infantil                                 ║
╚═══════════════════════════════════════════════════════════════╝

Objetivo: Identificar perfiles demográficos y territoriales de NNA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os
import gc  # Para limpiar memoria

# Configuración
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("Set2")

print("╔════════════════════════════════════════════════════════════╗")
print("║   ANÁLISIS DE SEGMENTACIÓN DEMOGRÁFICA - NNA              ║")
print("╚════════════════════════════════════════════════════════════╝")
print(f"\n📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# Cargar datos
print("📂 Cargando datos preparados...")
df = pd.read_csv('data/procesados/Base_NNA_trabajo_infantil.csv')
print(f"✓ Datos cargados: {df.shape[0]:,} registros\n")

# ═══════════════════════════════════════════════════════════════
# 1. PERFIL DEMOGRÁFICO GENERAL
# ═══════════════════════════════════════════════════════════════

print("="*70)
print("👥 PERFIL DEMOGRÁFICO DE NNA")
print("="*70 + "\n")

# Sexo
if 'SEXO' in df.columns:
    print("📊 DISTRIBUCIÓN POR SEXO:\n")
    sexo_dist = df['SEXO'].value_counts()
    for sexo, count in sexo_dist.items():
        pct = (count / len(df) * 100)
        print(f"   • {sexo}: {count} ({pct:.1f}%)")
    sexo_dominante = sexo_dist.idxmax()
    print(f"\n   ⭐ Sexo predominante: {sexo_dominante}")

# Ocupación
if 'OCUPACIÓN' in df.columns:
    print("\n\n📊 DISTRIBUCIÓN POR OCUPACIÓN:\n")
    ocup_dist = df['OCUPACIÓN'].value_counts().head(8)  # Top 8
    for ocup, count in ocup_dist.items():
        pct = (count / len(df) * 100)
        print(f"   • {ocup}: {count} ({pct:.1f}%)")

# Vínculo con jefe de hogar
if 'VÍNCULO_CON_EL_JEFE_DE_HOGAR' in df.columns:
    print("\n\n📊 VÍNCULO CON JEFE DE HOGAR:\n")
    vinculo_dist = df['VÍNCULO_CON_EL_JEFE_DE_HOGAR'].value_counts().head(6)
    for vinculo, count in vinculo_dist.items():
        pct = (count / len(df) * 100)
        print(f"   • {vinculo}: {count} ({pct:.1f}%)")

# Población diferencial
if 'POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN' in df.columns:
    print("\n\n📊 POBLACIÓN DIFERENCIAL (Top 5):\n")
    pobl_diff_dist = df['POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN'].value_counts().head(5)
    for pobl, count in pobl_diff_dist.items():
        if pd.notna(pobl):
            pct = (count / len(df) * 100)
            print(f"   • {pobl}: {count} ({pct:.1f}%)")

# ═══════════════════════════════════════════════════════════════
# 2. PERFIL LABORAL Y TERRITORIAL
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("💼 PERFIL LABORAL Y TERRITORIAL")
print("="*70 + "\n")

# NNA desvinculados laboralmente
if 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL' in df.columns:
    print("🔍 NNA DESVINCULADOS LABORALMENTE:\n")
    desv_dist = df['NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'].value_counts()
    for estado, count in desv_dist.items():
        pct = (count / len(df) * 100)
        print(f"   • {estado}: {count} ({pct:.1f}%)")

# Localidad
if 'LOCALIDAD' in df.columns:
    print("\n\n📍 DISTRIBUCIÓN POR LOCALIDAD (Top 5):\n")
    localidad_dist = df['LOCALIDAD'].value_counts().head(5)
    for localidad, count in localidad_dist.items():
        pct = (count / len(df) * 100)
        print(f"   • {localidad}: {count} ({pct:.1f}%)")

# Lugar de trabajo
if '¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?' in df.columns:
    print("\n\n🏭 LUGAR PRINCIPAL DE TRABAJO:\n")
    trabajo_dist = df['¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?'].value_counts()
    for lugar, count in trabajo_dist.items():
        if pd.notna(lugar):
            pct = (count / len(df) * 100)
            print(f"   • {lugar}: {count} ({pct:.1f}%)")

# Estrato - manejo especial para valores categóricos
if 'ESTRATO' in df.columns:
    print("\n\n🏠 DISTRIBUCIÓN POR ESTRATO:\n")
    estrato_dist = df['ESTRATO'].value_counts()
    for estrato, count in estrato_dist.items():
        if pd.notna(estrato):
            pct = (count / len(df) * 100)
            # Mostrar el estrato tal como está en los datos
            print(f"   • {estrato}: {count} ({pct:.1f}%)")

# ═══════════════════════════════════════════════════════════════
# 3. CRUCES ANALÍTICOS CLAVE
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("📊 CRUCES ANALÍTICOS CLAVE")
print("="*70 + "\n")

# Cruce 1: Sexo vs Desvinculación laboral
if 'SEXO' in df.columns and 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL' in df.columns:
    print("1️⃣  SEXO vs DESVINCULACIÓN LABORAL:\n")
    crosstab_sexo_desv = pd.crosstab(df['SEXO'], df['NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'],
                                     normalize='index') * 100
    print(crosstab_sexo_desv.round(1).to_string())

# Cruce 2: Ocupación vs Sexo
if 'OCUPACIÓN' in df.columns and 'SEXO' in df.columns:
    print("\n\n2️⃣  OCUPACIÓN vs SEXO (Top 5 ocupaciones):\n")
    top_ocupaciones = df['OCUPACIÓN'].value_counts().head(5).index
    df_top = df[df['OCUPACIÓN'].isin(top_ocupaciones)]
    crosstab_ocup_sexo = pd.crosstab(df_top['OCUPACIÓN'], df_top['SEXO'], normalize='index') * 100
    print(crosstab_ocup_sexo.round(1).to_string())

# ═══════════════════════════════════════════════════════════════
# 4. VISUALIZACIONES (VERSIÓN LIGERA - 4 GRÁFICOS)
# ═══════════════════════════════════════════════════════════════

os.makedirs('reports/segmentacion_nna', exist_ok=True)

print("\n\n" + "="*70)
print("📊 Generando visualizaciones (versión ligera)...")
print("="*70 + "\n")

# GRÁFICO 1: Dashboard Demográfico Básico (6 subplots)
print("Generando gráfico 1/4...")
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

# 1. Sexo
if 'SEXO' in df.columns:
    sexo_data = df['SEXO'].value_counts()
    axes[0,0].pie(sexo_data.values, labels=sexo_data.index, autopct='%1.1f%%', startangle=90)
    axes[0,0].set_title('Distribución por Sexo', fontweight='bold')

# 2. Desvinculación laboral
if 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL' in df.columns:
    desv_data = df['NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'].value_counts()
    colors = {'Sí': '#e74c3c', 'No': '#27ae60', 'other': '#95a5a6'}
    col_map = [colors.get(x, '#95a5a6') for x in desv_data.index]
    axes[0,1].pie(desv_data.values, labels=desv_data.index, autopct='%1.1f%%',
                  startangle=90, colors=col_map)
    axes[0,1].set_title('Desvinculación Laboral', fontweight='bold')

# 3. Ocupación (Top 6)
if 'OCUPACIÓN' in df.columns:
    ocup_data = df['OCUPACIÓN'].value_counts().head(6)
    axes[0,2].barh(range(len(ocup_data)), ocup_data.values, color='#9b59b6')
    axes[0,2].set_yticks(range(len(ocup_data)))
    axes[0,2].set_yticklabels([str(o)[:15]+'...' if len(str(o))>15 else str(o) for o in ocup_data.index], fontsize=8)
    axes[0,2].set_title('Ocupación (Top 6)', fontweight='bold')
    axes[0,2].invert_yaxis()

# 4. Vínculo hogar (Top 5)
if 'VÍNCULO_CON_EL_JEFE_DE_HOGAR' in df.columns:
    vinculo_data = df['VÍNCULO_CON_EL_JEFE_DE_HOGAR'].value_counts().head(5)
    axes[1,0].barh(range(len(vinculo_data)), vinculo_data.values, color='#e67e22')
    axes[1,0].set_yticks(range(len(vinculo_data)))
    axes[1,0].set_yticklabels([str(v)[:20]+'...' if len(str(v))>20 else str(v) for v in vinculo_data.index], fontsize=8)
    axes[1,0].set_title('Vínculo Hogar (Top 5)', fontweight='bold')
    axes[1,0].invert_yaxis()

# 5. Localidad (Top 5)
if 'LOCALIDAD' in df.columns:
    localidad_data = df['LOCALIDAD'].value_counts().head(5)
    axes[1,1].pie(localidad_data.values, labels=localidad_data.index, autopct='%1.1f%%', startangle=90)
    axes[1,1].set_title('Localidad (Top 5)', fontweight='bold')

# 6. Estrato - CORREGIDO: manejo de valores categóricos
if 'ESTRATO' in df.columns:
    estrato_data = df['ESTRATO'].value_counts()

    # Ordenar los estratos de manera lógica si es posible
    try:
        # Intentar extraer números para ordenar
        estrato_ordenado = sorted(estrato_data.index, key=lambda x:
                                 float(str(x).split('.')[0]) if '.' in str(x) else
                                 float(str(x).split()[0]) if str(x)[0].isdigit() else 999)
        estrato_data = estrato_data.reindex(estrato_ordenado)
    except:
        # Si falla, usar el orden original
        pass

    axes[1,2].bar(range(len(estrato_data)), estrato_data.values, color='#16a085')
    axes[1,2].set_xticks(range(len(estrato_data)))

    # Crear etiquetas truncadas para mejor visualización
    estrato_labels = []
    for estrato in estrato_data.index:
        if pd.isna(estrato):
            estrato_labels.append('N/A')
        else:
            estrato_str = str(estrato)
            # Truncar si es muy largo, mantener la parte numérica si existe
            if len(estrato_str) > 10:
                if '.' in estrato_str:
                    estrato_labels.append(estrato_str.split('.')[0] + '.')
                else:
                    estrato_labels.append(estrato_str[:8] + '...')
            else:
                estrato_labels.append(estrato_str)

    axes[1,2].set_xticklabels(estrato_labels, rotation=45, ha='right', fontsize=8)
    axes[1,2].set_title('Distribución por Estrato', fontweight='bold')
    axes[1,2].grid(axis='y', alpha=0.3)

plt.suptitle('PERFIL DEMOGRÁFICO Y TERRITORIAL DE NNA', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('reports/segmentacion_nna/01_dashboard_demografico.png', dpi=150, bbox_inches='tight')
plt.close()
gc.collect()  # Limpiar memoria
print("✓ Guardado: 01_dashboard_demografico.png")

# GRÁFICO 2: Sexo vs Ocupación (Heatmap)
print("Generando gráfico 2/4...")
if 'SEXO' in df.columns and 'OCUPACIÓN' in df.columns:
    fig, ax = plt.subplots(figsize=(10, 6))
    top_ocupaciones = df['OCUPACIÓN'].value_counts().head(8).index
    df_heat = df[df['OCUPACIÓN'].isin(top_ocupaciones)]
    crosstab = pd.crosstab(df_heat['OCUPACIÓN'], df_heat['SEXO'], normalize='index') * 100
    sns.heatmap(crosstab, annot=True, fmt='.1f', cmap='YlOrRd',
                cbar_kws={'label': 'Porcentaje (%)'}, ax=ax, linewidths=0.5)
    ax.set_title('Distribución de Sexo por Ocupación (%)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Sexo', fontweight='bold')
    ax.set_ylabel('Ocupación', fontweight='bold')
    plt.tight_layout()
    plt.savefig('reports/segmentacion_nna/02_sexo_ocupacion.png', dpi=150, bbox_inches='tight')
    plt.close()
    gc.collect()
    print("✓ Guardado: 02_sexo_ocupacion.png")

# GRÁFICO 3: Análisis Laboral
print("Generando gráfico 3/4...")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# 3.1 Desvinculación por sexo
if 'SEXO' in df.columns and 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL' in df.columns:
    crosstab_desv = pd.crosstab(df['SEXO'], df['NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'])
    crosstab_desv.plot(kind='bar', ax=axes[0], color=['#27ae60', '#e74c3c'])
    axes[0].set_title('Desvinculación Laboral por Sexo', fontweight='bold')
    axes[0].set_xlabel('Sexo', fontweight='bold')
    axes[0].set_ylabel('Frecuencia', fontweight='bold')
    axes[0].legend(title='Desvinculado', bbox_to_anchor=(1.05, 1), loc='upper left')
    axes[0].tick_params(axis='x', rotation=0)

# 3.2 Lugar de trabajo
if '¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?' in df.columns:
    trabajo_data = df['¿EN_DONDE_REALIZA_PRINCIPALMENTE_SU_TRABAJO?'].value_counts().head(6)
    axes[1].barh(range(len(trabajo_data)), trabajo_data.values, color='#3498db')
    axes[1].set_yticks(range(len(trabajo_data)))
    axes[1].set_yticklabels([str(t)[:25] for t in trabajo_data.index], fontsize=8)
    axes[1].set_xlabel('Frecuencia', fontweight='bold')
    axes[1].set_title('Lugar Principal de Trabajo', fontweight='bold')
    axes[1].invert_yaxis()

plt.suptitle('ANÁLISIS LABORAL DE NNA', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('reports/segmentacion_nna/03_analisis_laboral.png', dpi=150, bbox_inches='tight')
plt.close()
gc.collect()
print("✓ Guardado: 03_analisis_laboral.png")

# GRÁFICO 4: Población diferencial (Top 10)
print("Generando gráfico 4/4...")
if 'POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN' in df.columns:
    fig, ax = plt.subplots(figsize=(10, 6))
    pobl_data = df['POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN'].value_counts().head(10)
    ax.barh(range(len(pobl_data)), pobl_data.values, color='#8e44ad')
    ax.set_yticks(range(len(pobl_data)))
    ax.set_yticklabels([str(p)[:30]+'...' if len(str(p))>30 else str(p) for p in pobl_data.index], fontsize=8)
    ax.set_xlabel('Frecuencia', fontweight='bold')
    ax.set_title('Población Diferencial y de Inclusión (Top 10)', fontweight='bold')
    ax.invert_yaxis()
    plt.tight_layout()
    plt.savefig('reports/segmentacion_nna/04_poblacion_diferencial.png', dpi=150, bbox_inches='tight')
    plt.close()
    gc.collect()
    print("✓ Guardado: 04_poblacion_diferencial.png")

print("\n✅ Todas las visualizaciones completadas")

# ═══════════════════════════════════════════════════════════════
# 5. INSIGHTS Y RECOMENDACIONES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("💡 INSIGHTS Y RECOMENDACIONES")
print("="*70 + "\n")

print("📊 HALLAZGOS CLAVE:\n")

if 'SEXO' in df.columns:
    sexo_dominante = df['SEXO'].value_counts().idxmax()
    pct_sexo = (df['SEXO'].value_counts().max() / len(df) * 100)
    print(f"1. Distribución por sexo: {sexo_dominante} ({pct_sexo:.1f}%)")

if 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL' in df.columns:
    nna_trabajando = df[df['NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'] == 'Sí'].shape[0]
    pct_trabajando = (nna_trabajando / len(df) * 100)
    print(f"2. NNA trabajando: {nna_trabajando} ({pct_trabajando:.1f}%)")

if 'LOCALIDAD' in df.columns:
    localidad_principal = df['LOCALIDAD'].value_counts().idxmax()
    pct_localidad = (df['LOCALIDAD'].value_counts().max() / len(df) * 100)
    print(f"3. Localidad principal: {localidad_principal} ({pct_localidad:.1f}%)")

if 'OCUPACIÓN' in df.columns:
    ocupacion_principal = df['OCUPACIÓN'].value_counts().index[0]
    print(f"4. Ocupación principal: {ocupacion_principal}")

print("\n\n🎯 RECOMENDACIONES:\n")
print("1. Implementar programas de prevención focalizados por sexo y localidad")
print("2. Desarrollar estrategias de reintegración educativa para NNA trabajadores")
print("3. Fortalecer sistemas de protección en localidades con mayor prevalencia")
print("4. Crear programas de ocupación protegida para NNA en situación de trabajo")
print("5. Establecer alianzas con actores locales para intervención territorial")

# Exportar resumen
resumen = {
    'fecha_analisis': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'total_registros': int(len(df)),
    'visualizaciones_generadas': 4,
    'nna_trabajando': int(nna_trabajando) if 'nna_trabajando' in locals() else 0,
    'pct_trabajando': float(round(pct_trabajando, 2)) if 'pct_trabajando' in locals() else 0,
    'sexo_dominante': str(sexo_dominante) if 'sexo_dominante' in locals() else 'N/A'
}

import json
with open('reports/segmentacion_nna/resumen.json', 'w', encoding='utf-8') as f:
    json.dump(resumen, f, indent=2, ensure_ascii=False)

print("\n✓ Resumen exportado: reports/segmentacion_nna/resumen.json")

print("\n" + "="*70)
print("✅ ANÁLISIS DE SEGMENTACIÓN DE NNA COMPLETADO")
print(f"✅ Gráficos generados: 4")
print("="*70 + "\n")

from google.colab import drive
drive.mount('/content/drive')

#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
╔═══════════════════════════════════════════════════════════════╗
║  ANÁLISIS 4: TRABAJO INFANTIL EN BOGOTÁ                         ║
║  Base: df_subset_variables_seleccionadas.xlsx                 ║
╚═══════════════════════════════════════════════════════════════╝

Objetivo:
Analizar y diagnosticar la situación del trabajo infantil en Bogotá
a partir de registros sociales, familiares, de salud y laborales,
para apoyar la formulación de políticas públicas de protección a la niñez.
"""

# =====================================================================
# Importación de librerías
# =====================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os

# Configuración general
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("colorblind")
plt.rcParams['figure.figsize'] = (14, 8)

print("╔════════════════════════════════════════════════════════════╗")
print("║   ANÁLISIS DEL TRABAJO INFANTIL EN BOGOTÁ                 ║")
print("╚════════════════════════════════════════════════════════════╝")
print(f"\n📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# =====================================================================
# 1. CARGA DE DATOS
# =====================================================================
print("📂 Cargando base de datos...")
df = pd.read_excel('df_subset_variables_seleccionadas.xlsx')
print(f"✓ Datos cargados: {df.shape[0]:,} registros y {df.shape[1]} columnas\n")

# Mostrar primeras filas
print("📋 Vista previa de los datos:\n")
print(df.head(), "\n")

# =====================================================================
# 2. ANÁLISIS GENERAL DE LA POBLACIÓN NNA
# =====================================================================
print("="*70)
print("👧🧒 CARACTERIZACIÓN GENERAL DE LA POBLACIÓN NNA")
print("="*70 + "\n")

# Distribución por sexo
if 'SEXO' in df.columns:
    print("📊 Distribución por sexo:")
    sexo_dist = df['SEXO'].value_counts(dropna=False)
    sexo_pct = df['SEXO'].value_counts(normalize=True, dropna=False) * 100
    for cat, count in sexo_dist.items():
        print(f"   • {cat}: {count} ({sexo_pct[cat]:.1f}%)")
    print()

# Distribución por estrato
if 'ESTRATO_SOCIOECONÓMICO' in df.columns:
    print("📊 Distribución por estrato socioeconómico:")
    estrato_dist = df['ESTRATO_SOCIOECONÓMICO'].value_counts(dropna=False)
    estrato_pct = df['ESTRATO_SOCIOECONÓMICO'].value_counts(normalize=True, dropna=False) * 100
    for estrato, count in estrato_dist.items():
        print(f"   • Estrato {estrato}: {count} ({estrato_pct[estrato]:.1f}%)")
    print()

# Distribución por ocupación
if 'OCUPACIÓN' in df.columns:
    print("📊 Principales ocupaciones:")
    ocup_dist = df['OCUPACIÓN'].value_counts().head(5)
    for ocup, count in ocup_dist.items():
        print(f"   • {ocup}: {count}")
    print()

# =====================================================================
# 3. ANÁLISIS DEL TRABAJO INFANTIL
# =====================================================================
print("="*70)
print("🧱 ANÁLISIS DEL TRABAJO INFANTIL")
print("="*70 + "\n")

col_trabajo = 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'

if col_trabajo in df.columns:
    trabajo_dist = df[col_trabajo].value_counts(dropna=False)
    trabajo_pct = df[col_trabajo].value_counts(normalize=True, dropna=False) * 100

    print("📊 Estado de trabajo infantil:\n")
    for estado, count in trabajo_dist.items():
        print(f"   • {estado}: {count} ({trabajo_pct[estado]:.1f}%)")

    # Check if 'Si' or 'SI' are in the index before accessing
    pct_si = 0
    if 'Si' in trabajo_pct.index:
        pct_si += trabajo_pct['Si']
    if 'SI' in trabajo_pct.index:
        pct_si += trabajo_pct['SI']

    if pct_si > 20:
        print(f"\n⚠️ ALERTA: {pct_si:.1f}% de los NNA están o estuvieron en condición de trabajo.")
    else:
        print(f"\n💡 Nivel bajo de trabajo infantil reportado ({pct_si:.1f}%).")


# =====================================================================
# 4. PERFIL SOCIODEMOGRÁFICO DE NNA EN TRABAJO INFANTIL
# =====================================================================
print("\n\n" + "="*70)
print("👥 PERFIL SOCIODEMOGRÁFICO DE NNA EN TRABAJO INFANTIL")
print("="*70 + "\n")

if col_trabajo in df.columns and 'SEXO' in df.columns:
    print("📊 Distribución por sexo:\n")
    crosstab_sexo = pd.crosstab(df['SEXO'], df[col_trabajo], normalize='index') * 100
    print(crosstab_sexo.round(1).to_string())
    # Check for 'Si' and 'SI' columns
    if 'Si' in crosstab_sexo.columns or 'SI' in crosstab_sexo.columns:
        # Combine 'Si' and 'SI' for total incidence
        crosstab_sexo['Trabajo_Incidencia'] = 0
        if 'Si' in crosstab_sexo.columns:
            crosstab_sexo['Trabajo_Incidencia'] += crosstab_sexo['Si']
        if 'SI' in crosstab_sexo.columns:
            crosstab_sexo['Trabajo_Incidencia'] += crosstab_sexo['SI']

        if 'Trabajo_Incidencia' in crosstab_sexo.columns and not crosstab_sexo['Trabajo_Incidencia'].empty:
            menor_sexo = crosstab_sexo['Trabajo_Incidencia'].idxmax()
            print(f"\n   ⚠️ Mayor incidencia en: {menor_sexo} ({crosstab_sexo.loc[menor_sexo, 'Trabajo_Incidencia']:.1f}%)")


if col_trabajo in df.columns and 'ESTRATO_SOCIOECONÓMICO' in df.columns:
    print("\n\n📊 Distribución por estrato socioeconómico:\n")
    crosstab_estrato = pd.crosstab(df['ESTRATO_SOCIOECONÓMICO'], df[col_trabajo], normalize='index') * 100
    print(crosstab_estrato.round(1).to_string())
    # Check for 'Si' and 'SI' columns
    if 'Si' in crosstab_estrato.columns or 'SI' in crosstab_estrato.columns:
        # Combine 'Si' and 'SI' for total incidence
        crosstab_estrato['Trabajo_Incidencia'] = 0
        if 'Si' in crosstab_estrato.columns:
            crosstab_estrato['Trabajo_Incidencia'] += crosstab_estrato['Si']
        if 'SI' in crosstab_estrato.columns:
            crosstab_estrato['Trabajo_Incidencia'] += crosstab_estrato['SI']

        if 'Trabajo_Incidencia' in crosstab_estrato.columns and not crosstab_estrato['Trabajo_Incidencia'].empty:
            estrato_riesgo = crosstab_estrato['Trabajo_Incidencia'].idxmax()
            print(f"\n   ⚠️ Estrato con mayor riesgo: {estrato_riesgo} ({crosstab_estrato.loc[estrato_riesgo, 'Trabajo_Incidencia']:.1f}%)")


if col_trabajo in df.columns and 'LOCALIDAD' in df.columns:
    print("\n\n📊 Distribución por localidad:\n")
    crosstab_loc = pd.crosstab(df['LOCALIDAD'], df[col_trabajo], normalize='index') * 100
    # Check for 'Si' and 'SI' columns and combine for total incidence
    if 'Si' in crosstab_loc.columns or 'SI' in crosstab_loc.columns:
        crosstab_loc['Trabajo_Incidencia'] = 0
        if 'Si' in crosstab_loc.columns:
            crosstab_loc['Trabajo_Incidencia'] += crosstab_loc['Si']
        if 'SI' in crosstab_loc.columns:
            crosstab_loc['Trabajo_Incidencia'] += crosstab_loc['SI']

        if 'Trabajo_Incidencia' in crosstab_loc.columns and not crosstab_loc['Trabajo_Incidencia'].empty:
            top_loc = crosstab_loc['Trabajo_Incidencia'].sort_values(ascending=False).head(5)
            print(top_loc.round(1).to_string())
            print(f"\n   ✅ Localidades con más casos reportados: {', '.join(top_loc.index[:3])}")


# =====================================================================
# 5. CONDICIONES FAMILIARES Y SOCIALES
# =====================================================================
print("\n\n" + "="*70)
print("🏠 CONDICIONES FAMILIARES Y SOCIALES")
print("="*70 + "\n")

if col_trabajo in df.columns and 'VÍNCULO_CON_EL_JEFE_DE_HOGAR' in df.columns:
    print("📊 Relación entre vínculo familiar y trabajo infantil:\n")
    crosstab_vinc = pd.crosstab(df['VÍNCULO_CON_EL_JEFE_DE_HOGAR'], df[col_trabajo], normalize='index') * 100
    print(crosstab_vinc.round(1).to_string())

if col_trabajo in df.columns and 'POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN' in df.columns:
    print("\n\n📊 Análisis por población diferencial:\n")
    crosstab_pob = pd.crosstab(df['POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN'], df[col_trabajo], normalize='index') * 100
    print(crosstab_pob.round(1).to_string())

# =====================================================================
# 6. VISUALIZACIONES
# =====================================================================
print("\n\n" + "="*70)
print("📈 VISUALIZACIONES")
print("="*70 + "\n")

# Gráfico de barras: trabajo infantil por sexo
if col_trabajo in df.columns and 'SEXO' in df.columns:
    plt.figure()
    sns.countplot(data=df, x='SEXO', hue=col_trabajo)
    plt.title("Distribución del trabajo infantil por sexo")
    plt.xlabel("Sexo")
    plt.ylabel("Número de NNA")
    plt.legend(title='¿Desvinculado de actividad laboral?')
    plt.show()

# Gráfico de barras: trabajo infantil por estrato
if col_trabajo in df.columns and 'ESTRATO_SOCIOECONÓMICO' in df.columns:
    plt.figure()
    sns.countplot(data=df, x='ESTRATO_SOCIOECONÓMICO', hue=col_trabajo)
    plt.title("Trabajo infantil por estrato socioeconómico")
    plt.xlabel("Estrato")
    plt.ylabel("Número de NNA")
    plt.legend(title='¿Desvinculado?')
    plt.show()

# =====================================================================
# 7. CONCLUSIONES AUTOMÁTICAS
# =====================================================================
print("\n\n" + "="*70)
print("🧩 CONCLUSIONES GENERALES")
print("="*70 + "\n")

print("✅ Se realizó una caracterización general de la población NNA en Bogotá.")
print("✅ Se identificaron diferencias por sexo, estrato y localidad.")
print("✅ Se analizaron condiciones familiares y de vulnerabilidad social.\n")

# Check if 'Si' or 'SI' are in the index before accessing
total_si = 0
if 'Si' in trabajo_dist.index:
    total_si += trabajo_dist['Si']
if 'SI' in trabajo_dist.index:
    total_si += trabajo_dist['SI']

pct_si = (total_si / len(df) * 100) if len(df) > 0 else 0

print(f"📊 En total, {total_si} NNA ({pct_si:.1f}%) presentan o presentaron trabajo infantil.")
if pct_si > 25:
    print("⚠️  Este valor refleja una problemática significativa que requiere atención prioritaria.")
else:
    print("💡 El fenómeno del trabajo infantil, aunque presente, muestra una tendencia moderada.")

# ═══════════════════════════════════════════════════════════════
# 6. VISUALIZACIONES
# ═══════════════════════════════════════════════════════════════

os.makedirs('reports/trabajo_infantil', exist_ok=True)

print("\n\n" + "="*70)
print("📊 Generando visualizaciones del trabajo infantil...")
print("="*70 + "\n")

# Dashboard principal
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1️⃣ Estado de trabajo infantil (Sí / No)
col_trabajo = 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'
if col_trabajo in df.columns:
    trabajo_data = df[col_trabajo].value_counts()
    colors = {'Sí': '#e74c3c', 'No': '#27ae60', 'No reporta': '#95a5a6'}
    col_map = [colors.get(x, '#95a5a6') for x in trabajo_data.index]
    axes[0,0].pie(trabajo_data.values, labels=trabajo_data.index, autopct='%1.1f%%',
                  startangle=90, colors=col_map, textprops={'fontsize': 10})
    axes[0,0].set_title('Condición de Trabajo Infantil', fontsize=12, fontweight='bold')

# 2️⃣ Trabajo infantil por sexo
if 'SEXO' in df.columns and col_trabajo in df.columns:
    crosstab = pd.crosstab(df['SEXO'], df[col_trabajo])
    crosstab.plot(kind='bar', stacked=True, ax=axes[0,1],
                  color=['#27ae60', '#e74c3c', '#95a5a6'])
    axes[0,1].set_title('Trabajo Infantil por Sexo', fontsize=12, fontweight='bold')
    axes[0,1].set_xlabel('Sexo', fontweight='bold')
    axes[0,1].set_ylabel('Frecuencia', fontweight='bold')
    axes[0,1].legend(title='¿Desvinculado?', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
    axes[0,1].tick_params(axis='x', rotation=0)

# 3️⃣ Trabajo infantil por estrato
if 'ESTRATO_SOCIOECONÓMICO' in df.columns and col_trabajo in df.columns:
    crosstab = pd.crosstab(df['ESTRATO_SOCIOECONÓMICO'], df[col_trabajo])
    crosstab.plot(kind='bar', stacked=True, ax=axes[1,0],
                  color=['#27ae60', '#e74c3c', '#95a5a6'])
    axes[1,0].set_title('Trabajo Infantil por Estrato Socioeconómico', fontsize=12, fontweight='bold')
    axes[1,0].set_xlabel('Estrato', fontweight='bold')
    axes[1,0].set_ylabel('Frecuencia', fontweight='bold')
    axes[1,0].legend(title='¿Desvinculado?', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)

# 4️⃣ Trabajo infantil por localidad (Top 10)
if 'LOCALIDAD' in df.columns and col_trabajo in df.columns:
    top_loc = df['LOCALIDAD'].value_counts().head(10).index
    df_top_loc = df[df['LOCALIDAD'].isin(top_loc)]
    crosstab = pd.crosstab(df_top_loc['LOCALIDAD'], df_top_loc[col_trabajo])
    crosstab.plot(kind='barh', stacked=True, ax=axes[1,1],
                  color=['#27ae60', '#e74c3c', '#95a5a6'])
    axes[1,1].set_title('Trabajo Infantil por Localidad (Top 10)', fontsize=12, fontweight='bold')
    axes[1,1].set_xlabel('Frecuencia', fontweight='bold')
    axes[1,1].set_ylabel('Localidad', fontweight='bold')
    axes[1,1].legend(title='¿Desvinculado?', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)

plt.suptitle('DASHBOARD DE ANÁLISIS DEL TRABAJO INFANTIL EN BOGOTÁ', fontsize=16, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('reports/trabajo_infantil/01_dashboard_general.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: reports/trabajo_infantil/01_dashboard_general.png")
plt.close()


# ═══════════════════════════════════════════════════════════════
# 7. MAPA DE CALOR: VARIABLES SOCIALES Y FAMILIARES
# ═══════════════════════════════════════════════════════════════

if 'VÍNCULO_CON_EL_JEFE_DE_HOGAR' in df.columns and col_trabajo in df.columns:
    fig, ax = plt.subplots(figsize=(10, 6))
    crosstab = pd.crosstab(df['VÍNCULO_CON_EL_JEFE_DE_HOGAR'], df[col_trabajo], normalize='index') * 100
    sns.heatmap(crosstab, annot=True, fmt='.1f', cmap='RdYlGn_r',
                cbar_kws={'label': 'Porcentaje (%)'}, ax=ax, linewidths=0.5)
    ax.set_title('Trabajo Infantil según Vínculo Familiar (%)', fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Condición Laboral', fontweight='bold')
    ax.set_ylabel('Vínculo con el Jefe de Hogar', fontweight='bold')
    plt.tight_layout()
    plt.savefig('reports/trabajo_infantil/02_heatmap_vinculo.png', dpi=300, bbox_inches='tight')
    print("✓ Guardado: reports/trabajo_infantil/02_heatmap_vinculo.png")
    plt.close()


# ═══════════════════════════════════════════════════════════════
# 8. INSIGHTS Y RECOMENDACIONES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("💡 INSIGHTS Y RECOMENDACIONES")
print("="*70 + "\n")

print("📊 HALLAZGOS CRÍTICOS:\n")

if col_trabajo in df.columns:
    pct_trabajan = (df[col_trabajo] == 'Sí').sum() / len(df) * 100
    print(f"1. {pct_trabajan:.1f}% de los NNA registrados presentan o presentaron trabajo infantil.")
    if pct_trabajan > 25:
        print("   → Alta prevalencia: problema social estructural que requiere atención urgente.")
    else:
        print("   → Nivel moderado, pero persistente de trabajo infantil reportado.")

if 'ESTRATO_SOCIOECONÓMICO' in df.columns and col_trabajo in df.columns:
    crosstab_estrato = pd.crosstab(df['ESTRATO_SOCIOECONÓMICO'], df[col_trabajo], normalize='index') * 100
    if 'Sí' in crosstab_estrato.columns:
        estrato_max = crosstab_estrato['Sí'].idxmax()
        valor = crosstab_estrato.loc[estrato_max, 'Sí']
        print(f"\n2. Estrato {estrato_max} registra la mayor incidencia de trabajo infantil ({valor:.1f}%).")
        print("   → Asociado a vulnerabilidad económica y exclusión social.")

if 'LOCALIDAD' in df.columns and col_trabajo in df.columns:
    crosstab_loc = pd.crosstab(df['LOCALIDAD'], df[col_trabajo], normalize='index') * 100
    if 'Sí' in crosstab_loc.columns:
        top_3 = crosstab_loc['Sí'].sort_values(ascending=False).head(3)
        print(f"\n3. Localidades con mayor incidencia: {', '.join(top_3.index)}")
        print("   → Priorizar intervención territorial con enfoque diferencial.")

print("\n\n🎯 RECOMENDACIONES ESTRATÉGICAS:\n")
print("📍 POLÍTICAS Y PROGRAMAS:")
print("1. Fortalecer programas de erradicación del trabajo infantil en zonas críticas.")
print("2. Promover subsidios educativos y acompañamiento psicosocial.")
print("3. Impulsar alianzas interinstitucionales para prevención temprana.")
print("4. Implementar programas de sensibilización en escuelas y comunidades.")

print("\n📚 EDUCACIÓN Y PREVENCIÓN:")
print("5. Capacitaciones para familias sobre derechos de la niñez.")
print("6. Campañas en medios locales con testimonios y mensajes positivos.")
print("7. Inclusión de temas de trabajo infantil en currículos escolares.")

print("\n⚖️ GESTIÓN INSTITUCIONAL:")
print("8. Auditoría de reportes y verificación de seguimiento a casos.")
print("9. Integración de bases de datos entre entidades locales y nacionales.")
print("10. Indicadores de desempeño institucional para monitoreo continuo.")

print("\n🧩 ENFOQUE DIFERENCIAL:")
print("11. Acciones focalizadas según género y pertenencia a poblaciones diferenciales.")
print("12. Mayor presencia de programas en comunidades rurales y periféricas.")
print("13. Estrategias participativas con familias y líderes locales.")

# Exportar resumen
resumen = {
    'fecha_analisis': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'total_registros': int(len(df)),
    'porcentaje_trabajo_infantil': float(round(pct_trabajan, 2))
}

import json
with open('reports/trabajo_infantil/resumen.json', 'w', encoding='utf-8') as f:
    json.dump(resumen, f, indent=2, ensure_ascii=False)

print("\n✓ Resumen exportado: reports/trabajo_infantil/resumen.json")

print("\n" + "="*70)
print("✅ ANÁLISIS DE TRABAJO INFANTIL COMPLETADO")
print("="*70 + "\n")

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
╔═══════════════════════════════════════════════════════════════╗
║  ANÁLISIS 5: MODELADO PREDICTIVO                              ║
║  Trabajo Infantil en Bogotá                                   ║
╚═══════════════════════════════════════════════════════════════╝

Objetivo: Construir modelos predictivos para identificar
          factores que aumentan la probabilidad de que un
          niño, niña o adolescente (NNA) esté en condición
          de trabajo infantil.
"""

# ═══════════════════════════════════════════════════════════════
# 0. IMPORTACIÓN DE LIBRERÍAS
# ═══════════════════════════════════════════════════════════════

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os
import warnings
warnings.filterwarnings('ignore')

print("╔════════════════════════════════════════════════════════════╗")
print("║   MODELADO PREDICTIVO DE TRABAJO INFANTIL                 ║")
print("╚════════════════════════════════════════════════════════════╝")
print(f"\n📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# ═══════════════════════════════════════════════════════════════
# 1. CARGA DE DATOS
# ═══════════════════════════════════════════════════════════════

print("📂 Cargando datos preparados...")
df = pd.read_csv('data/procesados/Base_NNA_trabajo_infantil.csv')
print(f"✓ Datos cargados: {df.shape[0]:,} registros\n")

# ═══════════════════════════════════════════════════════════════
# 2. PREPARACIÓN DE DATOS PARA MODELADO
# ═══════════════════════════════════════════════════════════════

print("="*70)
print("🔧 PREPARACIÓN DE DATOS PARA MODELADO")
print("="*70 + "\n")

# Variable objetivo: NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL
target_col = 'NNA_DESVINCULADO_DE_LA_ACTIVIDAD_LABORAL'

if target_col not in df.columns:
    print(f"⚠️  Variable objetivo '{target_col}' no encontrada")
else:
    print(f"✓ Variable objetivo: {target_col}")

# Filtrar registros válidos
df_model = df[df[target_col].notna()].copy()
print(f"✓ Registros válidos para modelado: {len(df_model)} ({len(df_model)/len(df)*100:.1f}%)")

# Distribución de la variable objetivo
print(f"\n📊 Distribución de la variable objetivo (trabajo infantil):\n")
target_dist = df_model[target_col].value_counts()
for clase, count in target_dist.items():
    pct = (count / len(df_model) * 100)
    print(f"   • {clase}: {count} ({pct:.1f}%)")

# Variables predictoras candidatas
predictores = [
    'SEXO',
    'EDAD',
    'LOCALIDAD',
    'ESTRATO_SOCIOECONÓMICO',
    'OCUPACIÓN',
    'VÍNCULO_CON_EL_JEFE_DE_HOGAR',
    'ASISTE_A_LA_ESCUELA',
    'POBLACIÓN_DIFERENCIAL_Y_DE_INCLUSIÓN',
    'CONDICIÓN_DE_SALUD',
]

# Verificar qué columnas existen
predictores_disponibles = [p for p in predictores if p in df_model.columns]
print(f"\n✓ Variables predictoras disponibles: {len(predictores_disponibles)}")
for p in predictores_disponibles:
    print(f"   • {p}")

# ═══════════════════════════════════════════════════════════════
# 3. ANÁLISIS DE ASOCIACIONES (CHI-CUADRADO)
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("📊 ANÁLISIS DE ASOCIACIONES (Chi-Cuadrado)")
print("="*70 + "\n")

from scipy.stats import chi2_contingency

print("🔍 Significancia estadística de cada variable:")
print("(p-value < 0.05 = asociación significativa)\n")

chi2_results = []
for predictor in predictores_disponibles:
    ct = pd.crosstab(df_model[predictor], df_model[target_col])
    chi2, p_value, dof, expected = chi2_contingency(ct)
    chi2_results.append({
        'variable': predictor,
        'chi2': chi2,
        'p_value': p_value,
        'significativo': 'Sí' if p_value < 0.05 else 'No'
    })
    sig_icon = '✓' if p_value < 0.05 else '✗'
    print(f"   {sig_icon} {predictor}")
    print(f"      Chi² = {chi2:.2f}, p-value = {p_value:.4f}\n")

chi2_df = pd.DataFrame(chi2_results).sort_values('p_value')
print("\n📊 Variables más asociadas al trabajo infantil:\n")
for idx, row in chi2_df.head(5).iterrows():
    print(f"   {idx+1}. {row['variable']} → p-value = {row['p_value']:.4f}")

# ═══════════════════════════════════════════════════════════════
# 4. CODIFICACIÓN DE VARIABLES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("🔨 CODIFICACIÓN DE VARIABLES CATEGÓRICAS")
print("="*70 + "\n")

from sklearn.preprocessing import LabelEncoder

df_encoded = df_model[predictores_disponibles + [target_col]].copy()

encoders = {}
for col in predictores_disponibles:
    le = LabelEncoder()
    df_encoded[col] = df_encoded[col].fillna('Missing')
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    encoders[col] = le

le_target = LabelEncoder()
df_encoded[target_col] = le_target.fit_transform(df_encoded[target_col])

print(f"✓ Variables codificadas correctamente")
print(f"✓ Clases objetivo: {list(le_target.classes_)}")

X = df_encoded[predictores_disponibles]
y = df_encoded[target_col]

print(f"\n✓ X shape: {X.shape}")
print(f"✓ y shape: {y.shape}")

# ═══════════════════════════════════════════════════════════════
# 5. ENTRENAMIENTO DE MODELOS
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("🤖 ENTRENAMIENTO DE MODELOS PREDICTIVOS")
print("="*70 + "\n")

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

print(f"✓ Conjunto de entrenamiento: {len(X_train)} registros")
print(f"✓ Conjunto de prueba: {len(X_test)} registros\n")

modelos = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42, max_depth=10)
}

resultados = []
print("🔄 Entrenando modelos...\n")
for nombre, modelo in modelos.items():
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    cv_scores = cross_val_score(modelo, X_train, y_train, cv=5)
    resultados.append({
        'modelo': nombre,
        'accuracy_test': acc,
        'cv_mean': cv_scores.mean(),
        'cv_std': cv_scores.std()
    })
    print(f"✓ {nombre}: {acc:.3f} (CV: {cv_scores.mean():.3f} ± {cv_scores.std():.3f})")

resultados_df = pd.DataFrame(resultados).sort_values('accuracy_test', ascending=False)
print("\n📊 Ranking de modelos:\n", resultados_df)

mejor_modelo_name = resultados_df.iloc[0]['modelo']
mejor_modelo = modelos[mejor_modelo_name]
print(f"\n✓ Mejor modelo: {mejor_modelo_name}")

# ═══════════════════════════════════════════════════════════════
# 6. IMPORTANCIA DE VARIABLES
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "="*70)
print("🎯 IMPORTANCIA DE VARIABLES")
print("="*70 + "\n")

if hasattr(mejor_modelo, 'feature_importances_'):
    feature_imp = pd.DataFrame({
        'feature': predictores_disponibles,
        'importance': mejor_modelo.feature_importances_
    }).sort_values('importance', ascending=False)

    print("📊 Variables más importantes para predecir trabajo infantil:\n")
    for idx, row in feature_imp.head(5).iterrows():
        print(f"   • {row['feature']}: {row['importance']:.4f}")
else:
    print("⚠️  El modelo no tiene atributo de importancia de features.")

# ═══════════════════════════════════════════════════════════════
# 7. EVALUACIÓN Y VISUALIZACIONES
# ═══════════════════════════════════════════════════════════════

os.makedirs('reports/modelado_trabajo_infantil', exist_ok=True)

y_pred = mejor_modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm, index=le_target.classes_, columns=le_target.classes_)

print("\n📊 REPORTE DE CLASIFICACIÓN:\n")
print(classification_report(y_test, y_pred, target_names=le_target.classes_))
print("\n📊 MATRIZ DE CONFUSIÓN:\n")
print(cm_df)

# Visualización: comparación de modelos
fig, ax = plt.subplots(figsize=(8, 6))
sns.barplot(y='modelo', x='accuracy_test', data=resultados_df, palette='Blues_d')
plt.title('Comparación de Modelos - Predicción de Trabajo Infantil', fontsize=14, fontweight='bold')
plt.xlabel('Accuracy')
plt.ylabel('Modelo')
plt.tight_layout()
plt.savefig('reports/modelado_trabajo_infantil/01_comparacion_modelos.png', dpi=300)
plt.close()

# Visualización: importancia de variables
if hasattr(mejor_modelo, 'feature_importances_'):
    plt.figure(figsize=(10, 8))
    sns.barplot(x='importance', y='feature', data=feature_imp.head(10), palette='viridis')
    plt.title('Top 10 Variables Más Importantes', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('reports/modelado_trabajo_infantil/02_importancia_variables.png', dpi=300)
    plt.close()

# Visualización: matriz de confusión
plt.figure(figsize=(6, 5))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='RdYlGn', cbar=False)
plt.title('Matriz de Confusión - Trabajo Infantil', fontsize=14, fontweight='bold')
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.tight_layout()
plt.savefig('reports/modelado_trabajo_infantil/03_confusion_matrix.png', dpi=300)
plt.close()

print("\n✓ Gráficos guardados en reports/modelado_trabajo_infantil/\n")

# ═══════════════════════════════════════════════════════════════
# 8. INSIGHTS Y RECOMENDACIONES
# ═══════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("💡 INSIGHTS Y RECOMENDACIONES")
print("="*70 + "\n")

best_acc = resultados_df.iloc[0]['accuracy_test']
print(f"1️⃣ El mejor modelo ({mejor_modelo_name}) alcanzó {best_acc:.1%} de precisión.\n")

if hasattr(mejor_modelo, 'feature_importances_'):
    top_vars = feature_imp.head(3)
    print("2️⃣ Principales factores asociados al trabajo infantil:\n")
    for _, row in top_vars.iterrows():
        print(f"   • {row['feature']}: {row['importance']:.3f}")

print("\n🎯 RECOMENDACIONES DE POLÍTICA PÚBLICA:\n")
print("📚 EDUCACIÓN Y PREVENCIÓN:")
print("   - Fortalecer estrategias de permanencia escolar.")
print("   - Acompañamiento psicosocial a familias con alto riesgo.")
print("   - Programas de sensibilización en comunidades vulnerables.\n")

print("🏙️ ENFOQUE TERRITORIAL:")
print("   - Priorizar localidades con mayor probabilidad de trabajo infantil.")
print("   - Integrar análisis predictivo en la focalización de programas sociales.\n")

print("⚙️ MEJORAS DEL MODELO:")
print("   - Incluir variables económicas familiares (ingresos, desempleo).")
print("   - Agregar registros longitudinales para seguimiento temporal.")
print("   - Aumentar tamaño muestral para mejorar estabilidad del modelo.")

# Guardar resumen y modelo
resumen = {
    'fecha_analisis': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'mejor_modelo': mejor_modelo_name,
    'accuracy': float(round(best_acc, 3)),
    'n_predictores': len(predictores_disponibles)
}
if hasattr(mejor_modelo, 'feature_importances_'):
    resumen['top_3_variables'] = feature_imp.head(3)['feature'].tolist()

import json, pickle
with open('reports/modelado_trabajo_infantil/resumen.json', 'w', encoding='utf-8') as f:
    json.dump(resumen, f, indent=2, ensure_ascii=False)

with open('reports/modelado_trabajo_infantil/mejor_modelo.pkl', 'wb') as f:
    pickle.dump(mejor_modelo, f)

print("\n✓ Resumen y modelo guardados en reports/modelado_trabajo_infantil/")
print("\n" + "="*70)
print("✅ MODELADO PREDICTIVO DE TRABAJO INFANTIL COMPLETADO")
print("="*70 + "\n")